NRPT-306: Adds information modal
bcgov/mem-mmti-public pull request #312
Opened 2020-09-08 21:46 UTC by KitArmstrong

Ticket: https://bcmines.atlassian.net/browse/NRPT-306

This PR adds the config service that will load various configuration details on app load.  It uses this service to check if there are any messages that should be displayed to the user in a modal. When the user dismisses the the modal a cookie is set to prevent it from opening again unless a new message is added.

2020-09-09 16:22 UTC, mtCarto requested changes
Modal works given the modalMessage object manually, code looks good for this component. Config service aligns with the NRPTI one.

Looks like the configService is causing unit test failures though, will need to update them with that dependency.

2020-09-09 17:37 UTC, KitArmstrong commented
> Modal works given the modalMessage object manually, code looks good for this component. Config service aligns with the NRPTI one.
> 
> Looks like the configService is causing unit test failures though, will need to update them with that dependency.

Broken unit tests have been updated and ones that are no longer required have been removed.

2020-09-10 16:39 UTC, dhlevi approved these changes
👍 Works as expected with the communication package manually inserted.

2020-09-10 19:01 UTC, mtCarto approved these changes

2020-09-11 15:03 UTC, merged