NRPT-510: load all docs on project load
bcgov/mem-mmti-public pull request #334
Opened 2020-11-20 20:03 UTC by MaxWardle

https://bcmines.atlassian.net/browse/NRPT-510

2020-11-23 20:58 UTC, BcGovNeal requested changes
I think this PR is still missing the loading indicator.  All records are now loaded immediately when the page becomes ready, however there is still no loading indication when the project data is still being fetched.

To test this you can set the network speed to `3G` on the Network tab in Chrome to simulate slow connection.  If you reload the project detail page while using a slow connection, the browser will only display a header and footer while the project data is being loaded.  

If you click on the project from the project list page, then the browser stays on the project list page while the project is being loaded.  Both of these are not the desired behaviour.

2020-11-23 22:21 UTC, MaxWardle commented
> I think this PR is still missing the loading indicator. All records are now loaded immediately when the page becomes ready, however there is still no loading indication when the project data is still being fetched.
> 
> To test this you can set the network speed to `3G` on the Network tab in Chrome to simulate slow connection. If you reload the project detail page while using a slow connection, the browser will only display a header and footer while the project data is being loaded.
> 
> If you click on the project from the project list page, then the browser stays on the project list page while the project is being loaded. Both of these are not the desired behaviour.

Thanks I didn't know about that network feature, I'll make those changes  now

2020-11-24 00:20 UTC, BcGovNeal approved these changes

2020-11-24 22:28 UTC, mtCarto approved these changes
👍

2020-11-24 23:52 UTC, merged